### ISSUE TITLE
elastiq does not work with multiple networks possible

### ISSUE THREAD

**Issue by fanzago** [dberzano/elastiq#14]
If a tenant has more networks as lan and wan, the creation of VM  doesn't work. The 
error message in the log is 
"root ERROR [__init__.ec2_scale_up] Cannot run instance via EC2: check your "hard" quota "
(that is not so clear) and the traceback is

Traceback (most recent call last):
File "/usr/lib/python2.6/site-packages/elastiq/__init__.py", line 291, in ec2_scale_up
instance_type=cf['ec2']['flavour']
File "/usr/lib/python2.6/site-packages/boto/ec2/image.py", line 325, in run
tenancy=tenancy, dry_run=dry_run)
File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 935, in run_instances
verb='POST')
File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1177, in get_object
raise self.ResponseError(response.status, response.reason, body)
EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0"?>
<Response><Errors><Error><Code>NetworkAmbiguous</Code><Message>Multiple possible networks found, use a Network ID to be more specific.</Message></Error></Errors><RequestID>req-48643f37-7819-42c3-9acb-8833ee1c3602</RequestID></Response>
2016-07-06 15:37:05 root INFO [__init__.ec2_scale_up] VM launch fail. Requested: 1/2 | Success: 0 | Failed: 1
2016-07-06 15:37:10 root ERROR [__init__.ec2_scale_up] Cannot run instance via EC2: check your "hard" quota

**Comment by dberzano** [comment]
Hello @fanzago, thanks for your report. This is a bug indeed. The message saying to check your quota is there because in the vast majority of the cases you cannot run instances because of that, so take it as a hint. I'll fix it.
